/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type TranslationCache = {
  _id: string
  _type: 'translationCache'
  _createdAt: string
  _updatedAt: string
  _rev: string
  sourceText?: string
  targetLang?: 'en' | 'pt' | 'es'
  translatedText?: string
  timestamp?: string
  textHash?: string
}

export type Villa = {
  _id: string
  _type: 'villa'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  listingType?: 'rent' | 'sale'
  propertyType?: 'villa' | 'apartment' | 'land'
  location?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'location'
  }
  privateInfo?: string
  geopoint?: Geopoint
  featuredOnHomepage?: boolean
  homepageOrder?: 1 | 2 | 3 | 4
  description?: string
  fullDescription?: string
  homeFeatures?: Array<
    {
      _key: string
    } & HomeFeature
  >
  pricePerNight?: number
  pricePerWeek?: number
  salePrice?: number
  seasonalPrices?: Array<
    {
      _key: string
    } & SeasonalPrice
  >
  pricingDetails?: string
  bedrooms?: number
  bathrooms?: number
  guests?: number
  surface?: number
  landSurface?: number
  mainImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  mainImageUrl?: string
  galleryImages?: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  galleryImageUrls?: Array<string>
  videoUrl?: string
  videoFile?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
  amenities?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'equipment'
  }>
  tags?: Array<string>
  brochurePdf?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    media?: unknown
    _type: 'file'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type HomeFeature = {
  _type: 'homeFeature'
  title?: string
  description?: string
}

export type SeasonalPrice = {
  _type: 'seasonalPrice'
  seasonName?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'season'
  }
  dates?: string
  prices?: Array<
    {
      _key: string
    } & BedroomPrice
  >
}

export type BedroomPrice = {
  _type: 'bedroomPrice'
  bedrooms?: number
  price?: number
}

export type Location = {
  _id: string
  _type: 'location'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  order?: number
}

export type Season = {
  _id: string
  _type: 'season'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  name_en?: string
  order?: number
}

export type Equipment = {
  _id: string
  _type: 'equipment'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  name_en?: string
  icon?:
    | 'Wifi'
    | 'Wind'
    | 'Fan'
    | 'Waves'
    | 'ChefHat'
    | 'Car'
    | 'DoorOpen'
    | 'Droplets'
    | 'ShowerHead'
    | 'Sun'
    | 'Coffee'
    | 'Flower2'
    | 'Trees'
    | 'Speaker'
    | 'Dumbbell'
    | 'Tv'
    | 'Gamepad2'
    | 'Shield'
    | 'Lock'
    | 'Utensils'
    | 'Briefcase'
    | 'Baby'
    | 'Accessibility'
    | 'ShoppingBag'
    | 'Martini'
    | 'Music'
    | 'Video'
    | 'Bike'
    | 'Ship'
    | 'Anchor'
    | 'Key'
    | 'Star'
    | 'Trophy'
    | 'Activity'
    | 'Heart'
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type AllSanitySchemaTypes =
  | TranslationCache
  | Villa
  | SanityImageCrop
  | SanityImageHotspot
  | Geopoint
  | Slug
  | HomeFeature
  | SeasonalPrice
  | BedroomPrice
  | Location
  | Season
  | Equipment
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
export declare const internalGroqTypeReferenceTo: unique symbol
